export default [
  {
    Code: '',
    Name: '雀巢奶粉',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '雀巢奶粉 quechaonaifen qcnf ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2021-03-30T11:37:49.81',
    Id: 792
  },
  {
    Code: '',
    Name: '雀巢品牌',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 41,
    CategoryName1: 'YO供应链',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '雀巢品牌 quechaopinpai qcpp ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2021-03-30T11:24:59.957',
    Id: 791
  },
  {
    Code: '',
    Name: '小米（abcd）',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 2,
    CategoryName1: '省移动平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '小米（abcd） xiaomi（abcd） xm（abcd） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2021-03-01T15:53:21.51',
    Id: 790
  },
  {
    Code: '',
    Name: '北京普天太力通信科技有限公司重庆分公司',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '13368344666',
    Contact: '刁小龙',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '北京普天太力通信科技有限公司重庆分公司 beijingputiantailitongxinkejiyouxiangongsizhongqingfengongsi bjpttltxkjyxgszqfgs ',
    BankName: '中国工商银行xxx支部',
    BankNumber: '6223323389766554389210',
    CompanyCode: '00001',
    CreatedDate: '2020-10-27T14:37:22.97',
    Id: 783
  },
  {
    Code: '',
    Name: '金吉祥',
    Area: 520203,
    Address: '贵州茅台镇',
    Zip: '',
    Phone: '15123259434',
    Contact: '王',
    Status: 1,
    CategoryId: 5,
    CategoryName1: '厂家',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '金吉祥 jinjixiang jjx ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2020-09-21T10:35:53.157',
    Id: 782
  },
  {
    Code: '',
    Name: '南京苏宁',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: 'xx',
    Status: 1,
    CategoryId: 2,
    CategoryName1: '省移动平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '南京苏宁 nanjingsuning njsn ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2020-02-20T17:07:38.747',
    Id: 781
  },
  {
    Code: '',
    Name: '北京普天太力通讯科技有限公司',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '北京普天太力通讯科技有限公司 beijingputiantailitongxunkejiyouxiangongsi bjpttltxkjyxgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.273',
    Id: 35
  },
  {
    Code: '',
    Name: '荆州市天华（博鹰）商贸有限公司（步步高）',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '荆州市天华（博鹰）商贸有限公司（步步高） jingzhoushitianhua（boying）shangmaoyouxiangongsi（bubugao） jzsth（by）smyxgs（bbg） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.257',
    Id: 34
  },
  {
    Code: '',
    Name: '北京普天太力通讯科技有限公司石家庄分公司',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '18633985678',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '北京普天太力通讯科技有限公司石家庄分公司 beijingputiantailitongxunkejiyouxiangongsishijiazhuangfengongsi bjpttltxkjyxgssjzfgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.24',
    Id: 33
  },
  {
    Code: '',
    Name: '黄陂（oppo）武汉欧柏众汇科技有限公司',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '黄陂（oppo）武汉欧柏众汇科技有限公司 huangbei（oppo）wuhanoubaizhonghuikejiyouxiangongsi hb（oppo）whobzhkjyxgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.223',
    Id: 32
  },
  {
    Code: '',
    Name: '黄陂（步步高） 重庆翀旻电子更名为佳亿宏',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '黄陂（步步高） 重庆翀旻电子更名为佳亿宏 huangbei（bubugao）zhongqingchongmindianzigengmingweijiayihong hb（bbg） zqcmdzgmwjyh ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.207',
    Id: 31
  },
  {
    Code: '',
    Name: '手机.石家庄兴英电子有限公司（小米直供）',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '18831191703',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '手机.石家庄兴英电子有限公司（小米直供） shouji.shijiazhuangxingyingdianziyouxiangongsi（xiaomizhigong） sj.sjzxydzyxgs（xmzg） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.19',
    Id: 30
  },
  {
    Code: '',
    Name: '手机唐山市满忠商贸有限公司-G网（二部）',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '手机唐山市满忠商贸有限公司-G网（二部） shoujitangshanshimanzhongshangmaoyouxiangongsi-Gwang（erbu） sjtssmzsmyxgs-Gw（eb） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.17',
    Id: 29
  },
  {
    Code: '',
    Name: '维修衡水希光通信有限公司（华为维修配件）',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '维修衡水希光通信有限公司（华为维修配件） weixiuhengshuixiguangtongxinyouxiangongsi（huaweiweixiupeijian） wxhsxgtxyxgs（hwwxpj） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.157',
    Id: 28
  },
  {
    Code: '',
    Name: '深圳市爱施德股份有限公司-LG',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '深圳市爱施德股份有限公司-LG shenzhenshiaishidegufenyouxiangongsi-LG szsasdgfyxgs-LG ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.14',
    Id: 27
  },
  {
    Code: '',
    Name: '手机天音通信有限公司河北分公司-事业二部',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '手机天音通信有限公司河北分公司-事业二部 shoujitianyintongxinyouxiangongsihebeifengongsi-shiyeerbu sjtytxyxgshbfgs-syeb ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.123',
    Id: 26
  },
  {
    Code: '',
    Name: '联通华盛通信有限公司河南分公司（沃达丰）',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 11,
    CategoryName1: '第三方平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '联通华盛通信有限公司河南分公司（沃达丰） liantonghuashengtongxinyouxiangongsihenanfengongsi（wodafeng） lthstxyxgshnfgs（wdf） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.103',
    Id: 25
  },
  {
    Code: '',
    Name: '河北乐讯电子科技有限公司(宝树座机对公)',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '河北乐讯电子科技有限公司(宝树座机对公) hebeilexundianzikejiyouxiangongsi(baoshuzuojiduigong) hblxdzkjyxgs(bszjdg) ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.07',
    Id: 24
  },
  {
    Code: '',
    Name: '河北本德电子产品销售有限公司(S2部门)',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '河北本德电子产品销售有限公司(S2部门) hebeibendedianzichanpinxiaoshouyouxiangongsi(S2bumen) hbbddzcpxsyxgs(S2bm) ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.053',
    Id: 23
  },
  {
    Code: '',
    Name: '联通华盛通信有限公司河南分公司（沃达丰）',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '联通华盛通信有限公司河南分公司（沃达丰） liantonghuashengtongxinyouxiangongsihenanfengongsi（wodafeng） lthstxyxgshnfgs（wdf） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.037',
    Id: 22
  },
  {
    Code: '',
    Name: '东莞市优佳电子科技有限公司（赖小燕）配件',
    Area: 0,
    Address: '塘厦镇沙湖社区大龄边路15号B栋2楼',
    Zip: '',
    Phone: '15625761289',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '东莞市优佳电子科技有限公司（赖小燕）配件 dongwanshiyoujiadianzikejiyouxiangongsi（laixiaoyan）peijian dwsyjdzkjyxgs（lxy）pj ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29.017',
    Id: 21
  },
  {
    Code: '',
    Name: '河南便利购供应链管理有限公司（海陆通）',
    Area: 0,
    Address: '奥加栖商务1楼',
    Zip: '',
    Phone: '15538299300',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '河南便利购供应链管理有限公司（海陆通） henanbianligougongyinglianguanliyouxiangongsi（hailutong） hnblggylglyxgs（hlt） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:29',
    Id: 20
  },
  {
    Code: '',
    Name: '中国移动通信集团终端有限公司河南分公司',
    Area: 0,
    Address: '河南省',
    Zip: '',
    Phone: '13011111111',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '中国移动通信集团终端有限公司河南分公司 zhongguoyidongtongxinjituanzhongduanyouxiangongsihenanfengongsi zgydtxjtzdyxgshnfgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:28.98',
    Id: 19
  },
  {
    Code: '',
    Name: '中国移动通信集团终端有限公司河南分公司',
    Area: 0,
    Address: '河南省焦作市',
    Zip: '',
    Phone: '13462875144',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '中国移动通信集团终端有限公司河南分公司 zhongguoyidongtongxinjituanzhongduanyouxiangongsihenanfengongsi zgydtxjtzdyxgshnfgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:28.963',
    Id: 18
  },
  {
    Code: '',
    Name: '深圳市莱柯特科技发展有限公司郑州分公司',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '深圳市莱柯特科技发展有限公司郑州分公司 shenzhenshilaiketekejifazhanyouxiangongsizhengzhoufengongsi szslktkjfzyxgszzfgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:28.947',
    Id: 17
  },
  {
    Code: '',
    Name: '在哪购（北京）网络信息技术股份有限公司',
    Area: 110100,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '在哪购（北京）网络信息技术股份有限公司 zainagou（beijing）wangluoxinxijishugufenyouxiangongsi zng（bj）wlxxjsgfyxgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:28.93',
    Id: 16
  },
  {
    Code: '',
    Name: '周口智诚商贸有限公司BBK（NX电信）',
    Area: 411600,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 10,
    CategoryName1: '厂商',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '周口智诚商贸有限公司BBK（NX电信） zhoukouzhichengshangmaoyouxiangongsiBBK（NXdianxin） zkzcsmyxgsBBK（NXdx） ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-23T15:01:28.91',
    Id: 15
  },
  {
    Code: '',
    Name: '北京中关村',
    Area: 0,
    Address: '',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 9,
    CategoryName1: '第三方',
    CategoryName2: '北京',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '北京中关村 beijingzhongguancun bjzgc ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-22T17:06:39.573',
    Id: 14
  },
  {
    Code: '',
    Name: '广州OPPO',
    Area: 0,
    Address: '广州天河区',
    Zip: '',
    Phone: '',
    Contact: '',
    Status: 1,
    CategoryId: 5,
    CategoryName1: '厂家',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '广州OPPO guangzhouOPPO gzOPPO ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-11-22T17:06:39.493',
    Id: 13
  },
  {
    Code: '',
    Name: '华为旗舰机专供',
    Area: 410102,
    Address: '哈哈哈哈军',
    Zip: '',
    Phone: '13333332222',
    Contact: '大老板',
    Status: 1,
    CategoryId: 2,
    CategoryName1: '省移动平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '华为旗舰机专供 huaweiqijianjizhuangong hwqjjzg ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-10-18T09:43:07.713',
    Id: 12
  },
  {
    Code: '',
    Name: '京东1',
    Area: 410108,
    Address: '古荥',
    Zip: '',
    Phone: '18211902222',
    Contact: '陈俊磊',
    Status: 1,
    CategoryId: 2,
    CategoryName1: '省移动平台',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '京东1 jingdong1 jd1 ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-10-16T19:43:01.373',
    Id: 11
  },
  {
    Code: '',
    Name: '苏宁',
    Area: 410108,
    Address: '古荥',
    Zip: '',
    Phone: '18211902222',
    Contact: '陈俊磊',
    Status: 1,
    CategoryId: 0,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '苏宁 suning sn ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 10
  },
  {
    Code: '',
    Name: '歌耐',
    Area: 410104,
    Address: '通讯新天地',
    Zip: '',
    Phone: '13888899900',
    Contact: '常向辉',
    Status: 1,
    CategoryId: 0,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '歌耐 genai gn ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 9
  },
  {
    Code: '',
    Name: '云米公司',
    Area: 410101,
    Address: '郑州市',
    Zip: '',
    Phone: '17737532789',
    Contact: '王焕旭',
    Status: 1,
    CategoryId: 0,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '云米公司 yunmigongsi ymgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 8
  },
  {
    Code: '',
    Name: '新天地宏盛通讯',
    Area: 410104,
    Address: '郑州市新天地2D32',
    Zip: '',
    Phone: '15038288262',
    Contact: '巩旭光',
    Status: 1,
    CategoryId: 0,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '新天地宏盛通讯 xintiandihongshengtongxun xtdhstx ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 7
  },
  {
    Code: '',
    Name: '移动B2B',
    Area: 410105,
    Address: '经三路',
    Zip: '',
    Phone: '18211902223',
    Contact: '移动',
    Status: 1,
    CategoryId: 0,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '移动B2B yidongB2B ydB2B ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 5
  },
  {
    Code: '',
    Name: '小米直供',
    Area: 410105,
    Address: '万达中心',
    Zip: '',
    Phone: '15515876767',
    Contact: '周阳',
    Status: 1,
    CategoryId: 0,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '小米直供 xiaomizhigong xmzg ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 4
  },
  {
    Code: '',
    Name: '新天地宏光通讯',
    Area: 410104,
    Address: '通讯新天地',
    Zip: '',
    Phone: '18537127759',
    Contact: '乔真',
    Status: 1,
    CategoryId: 0,
    CategoryName1: '',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: '新天地宏光通讯 xintiandihongguangtongxun xtdhgtx ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 3
  },
  {
    Code: '',
    Name: 'vivo郑州公司',
    Area: 410103,
    Address: '东大街裕鸿花园',
    Zip: '',
    Phone: '17337112090',
    Contact: '李魏岩',
    Status: 1,
    CategoryId: 5,
    CategoryName1: '厂家',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo: 'vivo郑州公司 vivozhengzhougongsi vivozzgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 2
  },
  {
    Code: '',
    Name: '郑州欧康龙商贸有限公司',
    Area: 410103,
    Address: '郑州市东大街裕鸿花园',
    Zip: '',
    Phone: '13525530362',
    Contact: '刁海建',
    Status: 1,
    CategoryId: 5,
    CategoryName1: '厂家',
    CategoryName2: '',
    CategoryName3: '',
    Description: '',
    _SearchInfo:
      '郑州欧康龙商贸有限公司 zhengzhououkanglongshangmaoyouxiangongsi zzoklsmyxgs ',
    BankName: '',
    BankNumber: '',
    CompanyCode: '00001',
    CreatedDate: '2019-08-28T11:40:20.2',
    Id: 1
  }
]
